#!/bin/bash
#PBS -l walltime=8:00:00
#PBS -l ncpus=1,mem=1gb
#PBS -N COVID_April12Hes
#PBS -J 0-99

module load python/3.6.1

cd /working/lab_jamesr/lachlanHa/paper-covid-herd-hesitancy/code/models

variants=("delta" "omicron")
echo $PBS_ARRAY_INDEX
for variant in ${variants[@]}
do
	for agespec in {0..1}
	do
		echo $variant $agespec		
		python -c "from Hesitancy_SingleCoreRun import*; Hesitancy_SingleCoreRun ('April_12_2021',$agespec,'$variant',20,$PBS_ARRAY_INDEX)"
	done
done